### 
GET http://localhost:3000/mascotas/hello

### Consulta todas las mascotas
GET http://localhost:3000/mascotas

### Consulta una mascota por su id
GET http://localhost:3000/mascotas/2

### insertar una mascota
POST http://localhost:3000/mascotas
Content-Type: application/json

{
    "tipo": "Perro",
    "raza": "Chau-chau",
    "alimentacion": "croquetas",
    "vacunas": "El parvovirus canino, moquillo, hepatitis canina y la rabia",
    "edad": 1,
    "precio": 12000
}

### Elimina un registro de una mascota
DELETE http://localhost:3000/mascotas/7

### actualizar un registro
PUT http://localhost:3000/mascotas/1
Content-Type: application/json

{
    "precio": 20000,
    "vacunas": "antirabia y moquillo"
}

CRUD
### enviar saludo
GET http://localhost:3000/empleado/saludo

### consulta un empleado por su id (Read)
GET http://localhost:3000/empleados/2

### consultar todos los empleados 
GET http://localhost:3000/empleados

### Insertar un registro de empleado (Create
POST  http://localhost:3000/empleados
Content-Type: application/json

{
    "name":"Batman",
    "position":"Vigilante nocturno",
    "salary":1000,
    "email":"batman@dccomic.com"
}
### Eliminar un registro (Delete)
DELETE http://localhost:3000/empleados/2

### Actualizar registro
PUT http://localhost:3000/empleados/6
Content-Type:  application/json

{
    "salary":2000,
    "position": "vigilante matutino"
}